
MODEL:
  META_ARCHITECTURE: "fcn16s"

  BACKBONE:
    PRETRAINED: False

  REFINEMENT:
    NAME: 'fcn32s'
    WEIGHT: "/mnt/truenas/scratch/xingyu.liao/checkpoints/train_fcn32s/"

 DATASETS:
  ROOT: '/mnt/truenas/scratch/xingyu.liao/DATA/VOCdevkit/VOC2012'

SOLVER:
  MAX_EPOCHS: 11
  CHECKPOINT_PERIOD: 11

OUTPUT_DIR: "/mnt/truenas/scratch/xingyu.liao/checkpoints/train_fcn16s"
